name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6
    - name: Run phpunit
      run: |
        chmod -R 777 vendor/orchestra/testbench-core/laravel/bootstrap/cache
        make phpunit
